---
- hosts: aws_ec2
  become: yes
  connection: ssh
  remote_user: root

  vars:
    ansible_ssh_private_key_file: "/etc/ansible/mainkeypair.pem"
    ansible_ssh_user: "root"

  tasks:
    - name: install httpd
      action: yum name=httpd state=present

    - name: restart httpd
      service: name=httpd state=restarted

    - name: install git in dev server
      action: yum name=git state=present

    - name: get code from github
      git:
        repo: https://github.com/devops0014/mono-project.git
        dest: /var/www/html/
        version: front
